### ISSUE TITLE
Lack of documentation for the post processing step

### ISSUE THREAD

**Issue by david-bouyssie** [userbz/DeMix-Q#4]
In the readme file, you wrote:
_Collect output files from processes of TextExporter (output 16) and EICExtractor (output 20), and do the post processing as shown in the example iPython notebook in the script folder._

Could you please give more details about this procedure ?
Or at least an example of command line to use with the example dataset.

**Comment by userbz** [comment]
Hi,

I felt sorry that could not find enough time to improve the documentation of the workflow. 
Basically, in the second cell of the notebook, consensus_txt and eic_txt are the variables to change to pointing the outputs from OpenMS. 
Now I Just updated an new script (works with Python2.7 and 3.5), which you can use instead of the notebook to do post-processing. 

Drop me an email if you find any problem. 

Best

**Comment by david-bouyssie** [comment]
Thank you for providing this alternative solution.

I tried to use this script on my output files.
I have two data files for my tests.
Here is the command I used:
DeMixQ_data_processing.py -consensus consensus.csv -eic eic.csv -n_samples 2 -n_repeats 1 -out peptides.csv

It first failed because it complained that some Python modules were missing. I had to perform the following installations (OS=Windows, python version=2.7 x86):
python -m pip install scikit-learn
python -m pip install numpy-1.11.2+mkl-cp27-cp27m-win32.whl
python -m pip install scipy-0.18.1-cp27-cp27m-win32.whl

However it still fails with the following error:

```
Traceback (most recent call last):
  File "D:\Logiciels\OpenMS\DeMixQ_data_processing.py", line 404, in <module>
    main()
  File "D:\Logiciels\OpenMS\DeMixQ_data_processing.py", line 177, in main
    eic = read_eic(eic_txt)
  File "D:\Logiciels\OpenMS\DeMixQ_data_processing.py", line 74, in read_eic
    sample_header = [i for i in fh.__next__().rstrip().split(',')
AttributeError: 'file' object has no attribute '__next__'
```

**Comment by userbz** [comment]
Hi,
My fault of using Python3 syntax in the script.
now I changed the use of **iter.**next**()** to **next(iter)**

This update will work on both Python2.7 and 3.5

Please try again.

**Comment by crumbpicker** [comment]
Thank you very much for this fix !
I successfully obtained my peptide table.
My goal is to generate a protein table so it would be nice to have the accession number in the final table.
I think I could find a way to deal with that but if you have time to add this column in the output file it would be great !

Thanks again !

**Comment by userbz** [comment]
@crumbpicker you are welcome. 
In my humble opinion, protein quantification is totally a different problem compared to peptide quantification; summing or averaging peptide abundances would not be accurate. The difficulty comes from not only the protein inference, but also the enormous differences of ionizing peptides.
